name: CompatHelper

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  compat-helper:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: JuliaRegistries/compathelper-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ssh: ${{ secrets.DOCUMENTER_KEY }}
