name: Documentation

on:
  push:
    branches: [main]
    tags: [v*]
  pull_request:

jobs:
  # documenter
  documenter:
    name: Documenter
    runs-on: ubuntu-latest
    steps:
      - name: Environment setup
        uses: actions/checkout@v3
      - name: Build package
        uses: julia-actions/julia-buildpkg@latest
      - name: Build and deploy documentation
        uses: julia-actions/julia-docdeploy@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
