name: Unit tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 2 1 * *'

jobs:
  unittest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        julia-version: ['1.3', '1', 'nightly']
    steps:
      - name: Environment setup
        uses: actions/checkout@v3
      - name: Julia setup
        uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - name: Build package
        uses: julia-actions/julia-buildpkg@latest
      - name: Run tests
        uses: julia-actions/julia-runtest@latest
      - name: CodeCov
        uses: julia-actions/julia-uploadcodecov@latest
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
